### ISSUE TITLE
Error when EnvEditor::getKey

### ISSUE THREAD

**Issue by guillmz** [GeoSot/Laravel-EnvEditor#1]
Hi there 

I having a trouble when I tried to get a key using:
` EnvEditor::getKey(string $key, $default = null) `

This is my code:
`public function index()
    {
        $key = 'APP_NAME';
        return EnvEditor::getKey(string $key, $default = null);    
    }`

And I getting this error : "syntax error, unexpected '$key' (T_VARIABLE), expecting ',' or ')'"
Any suggestion to fix this ?

Thanks .

**Comment by GeoSot** [comment]
Hello @guillmz 
Try this

```

public function index() {
$key = 'APP_NAME'; 
return EnvEditor::getKey($key,  null); 
}

```
