### ISSUE TITLE
Missing route name

### ISSUE THREAD

**Issue by WBDC** [GeoSot/Laravel-EnvEditor#13]
Hi, 

Currently I use permissions for each route. This requires each route must have a name. 

While I was testing your package I found 2 routes without name. 
These routes are:
| Method 	| URI            	| Name 	| Action                                               	|
|--------	|----------------	|------	|------------------------------------------------------	|
| DELETE 	| env-editor/key 	|      	| GeoSot\EnvEditor\Controllers\EnvController@deleteKey 	|
| PATCH  	| env-editor/key 	|      	| GeoSot\EnvEditor\Controllers\EnvController@editKey   	|

Although I could name the routes in the vendor folder, but it would be overwritten by a future update. 
![image](https://user-images.githubusercontent.com/50083290/113772460-a222cc00-971c-11eb-99cf-055849563c36.png)

Could you please look into this?

Many thanks

**Comment by WBDC** [comment]
**UPDATE:** 
The easier fix is to create a middleware which can be added to the `env-editor.php` config file.

**Comment by GeoSot** [comment]
Like this ?
https://github.com/GeoSot/Laravel-EnvEditor/blob/81b02e07c8ad09ded28f06733fe2aa4d17e23f2d/config/env-editor.php#L30

**Comment by WBDC** [comment]
> Like this ?
> https://github.com/GeoSot/Laravel-EnvEditor/blob/81b02e07c8ad09ded28f06733fe2aa4d17e23f2d/config/env-editor.php#L30

It is a solution (see my updated comment https://github.com/GeoSot/Laravel-EnvEditor/issues/13#issuecomment-814420340) 

In this application I use Laratrust (https://github.com/santigarcor/laratrust), which also allows to attach permissions to the user. My approach is to differentiate between functions is the route name. Bare in mind, that this is a very easy approach in Laratrust, hence I used this approach. 

Just out of curiosity, is it any reason why those 2 routes don't have names?

Thanks
A

**Comment by GeoSot** [comment]
>In this application I use Laratrust (https://github.com/santigarcor/laratrust),

Beloved package 💯 

>Just out of curiosity, is it any reason why those 2 routes don't have names?

If I can recall correct , has to do with :
https://github.com/GeoSot/Laravel-EnvEditor/blob/81b02e07c8ad09ded28f06733fe2aa4d17e23f2d/src/resources/views/components/_itemModal.blade.php#L139
