### ISSUE TITLE
Incorrect path for file system

### ISSUE THREAD

**Issue by DLO33** [GeoSot/Laravel-EnvEditor#2]
Helpers/EnvFilesManager.php
$this->getEnvDir(**true**) . $this->getEnvFileName() :

Please make the Boolean a configuration option as my file system cannot handle backwards slash.

For example, current code doesn't work: /var/www/html/site\.env

```
public function getFilePath(string $fileName = '')
    {
        $path = (empty($fileName)) ?
            $this->getEnvDir(true) . $this->getEnvFileName() :
            $this->getBackupsDir(true) . $fileName;
        if ($this->filesystem->exists($path)) {
            return $path;
        } else {
            throw new EnvException(__($this->package . '::exceptions.fileNotExists', ['name' => $path]), 0);
        }
    }
```

**Comment by GeoSot** [comment]
@DLO33 make, a try and tell my if this commit, solves your problem

**Comment by sheriffmarley** [comment]
When will the fix be available through composer?

**Comment by GeoSot** [comment]
@sheriffmarley 
You can try a composer update. I have pushed  0.9.4 version
