### ISSUE TITLE
Error when I try to modify a key

### ISSUE THREAD

**Issue by jtirado1996** [GeoSot/Laravel-EnvEditor#28]
I got this error

```
patch http://127.0.0.1:8000/env-editor/key net::ERR_EMPTY_RESPONSE
```
When I try to change one of my keys
I tested changing patch to PATCH and it worked

**Comment by jtirado1996** [comment]
It can be solved if I change 
_itemModal.blade
```
  getAjaxMethod() {
      switch (this.type) {
          case 'delete':
              return 'delete';
          case 'edit':
              return 'patch';
          default:
               return 'post'
                    }
                },
```
To uppercase

```
  getAjaxMethod() {
      switch (this.type) {
          case 'delete':
              return 'delete';
          case 'edit':
              return 'PATCH';
          default:
               return 'post'
                    }
                },
```

**Comment by jtirado1996** [comment]
https://github.com/GeoSot/Laravel-EnvEditor/blob/0cf5ebe510a404862d83992974169a2d5e155968/resources/views/components/_itemModal.blade.php#L114
this

**Comment by GeoSot** [comment]
I have created a branch [fix-28](https://github.com/GeoSot/Laravel-EnvEditor/tree/fix-28) with the proposed change.
Please try to fetch it with your composer  (just replace the package version with "dev-fix-28"), publish the files, and give me feedback if it is ok with this change
