### ISSUE TITLE
🐞 Bug - PHP 8.X - Index 404 + Empty `_currentEnv` table

### ISSUE THREAD

**Issue by Rikj000** [GeoSot/Laravel-EnvEditor#32]
## Issue description
After upgrading to PHP 8.X *(Currently on PHP 8.1 and Laravel 9.X)*,   
the `env-editor/` route started returning 404 as following:
```log
Not Found
The requested resource /env-editor was not found on this server.
```

When checking through `php artisan route:list | grep env-editor`,   
I can see that the route is being registered:
```log
GET|HEAD   env-editor/ .................... env-editor.index › GeoSot\EnvEditor › EnvController@index
```

## Work around
After registering following route in `routes.php`, I can access the GUI through `/env-editor/index`:
```php
Route::get('/env-editor/index', [EnvController::class, 'index'])->name('env-editor.index-workaround');
```

However this still leads to no `.env` settings being loaded/displayed.
*(Due to the `getItemsWithAjax()` in `_currentEnv.blade.php`, which still calls the bugged `env-editor.index` route)*

**Comment by GeoSot** [comment]
@Rikj000 are you sure of this?

I've just tried to replicate the issue, but seems to work as before (L9 - php 8.1.7)
![image](https://user-images.githubusercontent.com/22406063/233739218-d9ffd882-6d0c-4096-b23b-6db3cd667d05.png)


of course I tried your suggestion too, but seems to work the exact same way :confused:

**Comment by Rikj000** [comment]
Interesting! :thinking: 

I've struggled for a whole day trying to make env-editor work again,
after updating the project of my company,
which makes use of env-editor, to PHP 8.1.

Tested on:
- Both Linux and Windows, with similar 404 responses.
- env-editor 0.9.x and 2.x.x

Did multiple cache clears / optimize clears,
even deleted the whole vendor folder a few times without success.

I'll try again this monday, with "an empty example project",
when I'm back @ work and will keep you posted about my findings.

**Comment by Rikj000** [comment]
@GeoSot, I will be closing this issue + PR #33 

I tested with "an empty example project",   
with Laravel `v10.8.0` + Laravel-EnvEditor `v2.1.0`.

And can confirm that this is **not an issue** with Laravel-EnvEditor,   
but solely an issue with the project of my company.

Zipped my screenshot with proof, due to Github complaining about it
*(I guess due to it's resolution being 5154x1318px.. :innocent:)*
[Laravel-10.8.0-EnvEditor-2.1.0-Working.zip](https://github.com/GeoSot/Laravel-EnvEditor/files/11308149/Laravel-10.8.0-EnvEditor-2.1.0-Working.zip)

**Comment by GeoSot** [comment]
Thank you a lot for your feedback

**Comment by Rikj000** [comment]
I managed to resolve the issue in my project through [this StackOverflow answer](https://stackoverflow.com/a/25031920).

Somehow an empty `public/env-editor/` folder got created,   
which ended up being the culprit.

As soon as I deleted that empty `public/env-editor/` folder,   
the `/env-editor` route started working as expected again! :tada:
