### ISSUE TITLE
No values are displayed

### ISSUE THREAD

**Issue by huantt** [GeoSot/Laravel-EnvEditor#6]
I deployed and get no lines in Current .env file Content.
However, when I tried to download .env file in backups tab, It exists.

**Comment by huantt** [comment]
I've found problem when I saw the console.
Our website's using https, so it block http request in this code block:
```javascript
 submit() {
                    axios({
                        method: this.getAjaxMethod(),
                        _token:'1NxvyeO3bIztp7fbMSsUJWDBA9iSAzwi71DbPJt6',
                        url: 'http://dev.mydomain.com/env-editor/key',
                        data: this.modalItem
                    }).then((response) => {
                        if (response.data.message) {
                            envAlert('info', response.data.message);
                        }
                        envEventBus.$emit('env:changed')

                    }).catch((error) => {
                        envAlert('danger', error.response.data.message);
                    }).then(() => {
                        this.hideModal();
                    });
                },
```

How can I config schema or can you get dynamic schema by "//"?

**Comment by GeoSot** [comment]
Hello @huantt 
As I saw I use the following code. 
``` url: '{{route(config($package.'.route.name').'.key')}}'```
So I suppose that if you have set you laravel app to work on secure protocol, the route will be fine. 
I will check it later. Sorry for the delay

**Comment by huantt** [comment]
Thank you, I've found the problem, because I'm using cloudflare as proxy and my app can not get the exactly protocol
